
DROP SCHEMA IF EXISTS STAMFORD_USERS;
CREATE SCHEMA IF NOT EXISTS STAMFORD_USERS;
USE STAMFORD_USERS;

CREATE TABLE IF NOT EXISTS CAMPERS(
	ID INT auto_increment,
	CAMPERNAME VARCHAR(100) NOT NULL,
	primary key(ID)
);

insert into CAMPERS values(null, "Test");